# This workflow will build and push a new version to Amazon S3,

on:
  release:
    types: [created]

name: Deploy to Amazon S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: '14.x'

    - name: Build and deploy to Amazon S3
      id: build-image
      run: |
        npm install
        npm run deploy
