name: Build collaborative-book-client

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: '14.x'

    - name: Npm cache
      uses: actions/cache@v2.1.1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.OS }}-
    - name: Install npm dependencies
      run: npm ci

    - name: Build collaborative-book-client
      run: |
        npm run build

    - name: Upload collaborative-book-client
      uses: actions/upload-artifact@v2
      with:
        name: cb-client-artifact
        path: dist/
