name: Deploy collaborative-book-client

on:
  release:
    types: [created]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Download collaborative-book-client artifact
      uses: actions/download-artifact@v2
      with:
        name: cb-client-artifact

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy to Amazon S3
      run: |
        s3 sync ./dist s3://collaborative-book/ --delete
