name: Deploy

on:
  release:
    types: [created]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Download collaborative-book-client artifact
      uses: actions/download-artifact@v2
      with:
        name: cb-client-artifact

    - name: Deploy to Amazon S3
      run: |
        s3 sync ./dist s3://collaborative-book/ --delete
